name: healio_app
description: "A Flutter project for graduation project - named Healio App for finding and booking beauty care."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.25.0
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^10.12.0
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.2
  shimmer_animation: ^2.2.2+1
  smooth_page_indicator: ^2.0.1
  supabase_flutter: ^2.12.0
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.4
  app_links: ^6.4.1
  pinput: ^6.0.2
  gotrue: ^2.18.0
  google_sign_in: ^7.2.0
  equatable: ^2.0.8
  loading_animation_widget: ^1.3.0
  flutter_facebook_auth: ^7.1.6
  intl: ^0.20.2
  flutter_neat_and_clean_calendar: ^0.4.16
  table_calendar: ^3.2.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo-app-2.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/convenience-store.png
    - assets/icons/google-icon-logo.svg
    - assets/icons/facebook-logo-icon.svg
    - assets/icons/email-icon.svg
    - assets/icons/profile-icon.svg
    - assets/icons/lock-circle-icon.svg
    - assets/icons/nail.png
    - assets/icons/eyelashes.png
    - assets/icons/massage-bed.png
    - assets/icons/massage.png
    - assets/icons/barber-chair.png
    - assets/icons/lipstick.png
    - assets/icons/heart-arrow.png

    - assets/images/logo-healio-app.png
    - assets/images/logo-healio-app-2.png
    - assets/images/user-avatar-default.png
    - assets/images/massage-banner.png
    - assets/images/hair-salon-banner.jpeg
    - assets/images/spa-banner.webp
    - assets/images/medspa-banner.webp
    - assets/images/nail-banner.jpg
    - assets/images/barber-banner.jpg
    - assets/images/aesthetic.png
    - assets/images/barbering.png
    - assets/images/body.png
    - assets/images/hair-and-styling.webp
    - assets/images/makeup.jpg
    - assets/images/massage.jpg
    - assets/images/nail.jpeg
    - assets/images/spa.png
    - assets/images/tattoo.png


    - .env
